import { UserRole } from '@ecommerce/shared-kernel';

/**
 * User domain entity
 */
export class User {
  constructor(
    public readonly id: string,
    public readonly email: string,
    public readonly password: string,
    public readonly firstName?: string,
    public readonly lastName?: string,
    public readonly role: UserRole = UserRole.USER,
    public readonly createdAt: Date = new Date(),
    public readonly updatedAt: Date = new Date()
  ) {}

  static create(data: {
    email: string;
    password: string;
    firstName?: string;
    lastName?: string;
    role?: UserRole;
  }): User {
    // ID will be generated by Prisma (UUID)
    const id = this.generateId();
    return new User(
      id,
      data.email,
      data.password,
      data.firstName,
      data.lastName,
      data.role || UserRole.USER
    );
  }

  private static generateId(): string {
    // Generate UUID v4 format
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
      const r = (Math.random() * 16) | 0;
      const v = c === 'x' ? r : (r & 0x3) | 0x8;
      return v.toString(16);
    });
  }
}

